name: Kilted Pipes
favicon: null
layout_spectrum: 0.6610438234638423
typography_spectrum: 0.7431089314632118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3294463756028563
  lightness: 0.9581685832235962
  saturation: 0.722651794552803
  rhythmicContrast: 0.4806769306305796
purpose: []
